services:
  app:
    build: ./
    volumes:
      - .:/app
    ports:
     - 8206:8000


  db:
    image: mysql:8.3
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3377:3306
    environment:
      MYSQL_DATABASE: tools_sql
      MYSQL_ROOT_PASSWORD: tools_sql_8206

volumes:
  db:
